--liquibase formatted sql

--changeset A.Mirhosseini:db.changelog-20240424-2047-wallet-table
CREATE TABLE USER
(
    ID       BIGINT UNIQUE       NOT NULL,
    USERNAME VARCHAR(255) UNIQUE NOT NULL,
    VERSION  BIGINT              NOT NULL DEFAULT 0,
    PRIMARY KEY (ID)
);

CREATE TABLE WALLET
(
    USER_ID BIGINT UNIQUE NOT NULL,
    BALANCE BIGINT        NOT NULL DEFAULT 0,
    VERSION BIGINT        NOT NULL DEFAULT 0,
    PRIMARY KEY (USER_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER (ID)
);

CREATE TABLE WALLET_TRANS
(
    ID       BIGINT UNIQUE       NOT NULL AUTO_INCREMENT,
    TRANS_TYPE VARCHAR(255) NOT NULL,
    USER_ID BIGINT,
    CREATE_AT BIGINT        NOT NULL,
    AMOUNT BIGINT NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (USER_ID) REFERENCES USER (ID)
);

INSERT INTO USER(ID, USERNAME) VALUES (1, "admin1");
INSERT INTO WALLET(USER_ID) VALUES (1);
