version: "3.7"
services:
  mysql:
    image: mysql:8.1
    container_name: mysql-wallet-balance
    ports:
      - 3306:3306
    hostname: localhost
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: wallet_test
    networks:
      - "wallet-balance"
    volumes:
      - /home/atousa/db/mysql/data/wallet:/var/lib/mysql
      - /home/atousa/db/mysql/init/wallet:/docker-entrypoint-initdb.d/:ro
  wallet-balance:
    build: ./
    ports:
      - "8080:8080"
    hostname: localhost
    networks:
      - "wallet-balance"
    depends_on:
      - mysql
    command: ["/home/files/wait-for-it.sh", "-t", "60", "-s", "mysql:3306", "--", "java", "-Dspring.profiles.active=docker", "-jar", "/home/files/wallet-balance-1.0-SNAPSHOT.jar"]
networks:
  wallet-balance: {}


