server:
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wallet_test
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  liquibase:
    enabled: true
    url: jdbc:mysql://localhost:3306/wallet_test
    user: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    change-log: classpath:/db/changelog/db.changelog-master.yaml

wallet:
  config:
    cron:
      daily-amount: "0 00 1 * * *"
    balance:
      min: 0